id: swagger-api

info:
  name: Public Swagger API - Detect
  author: pdteam,c-sh0,leadlife
  severity: high
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: "http.title:\"swagger\""
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - "/__swagger__/"
        - "/_swagger_/"
        - "/;/%20/swagger-ui.html"
        - "/..;/api/v1/api-docs"
        - "/..;/api/v2/api-docs"
        - "/..;/api/v3/api-docs"
        - "/..;/v1/api-docs"
        - "/..;/v2/api-docs"
        - "/..;/v3/api-docs"
        - "/..;api-docs"
        - "/api"
        - "/api_docs"
        - "/api-doc"
        - "/api-docs"
        - "/api-docs/"
        - "/api-docs/index.html"
        - "/api-docs/swagger-ui.html"
        - "/api-docs/swagger-ui/index.html"
        - "/api-docs/swagger.json"
        - "/api-docs/swagger.yaml"
        - "/api/__swagger__/"
        - "/api/_swagger_/"
        - "/api/api-docs"
        - "/api/api-docs/swagger.json"
        - "/api/api-docs/swagger.yaml"
        - "/api/apidocs"
        - "/api/apidocs/swagger.json"
        - "/api/apidocs/swagger.yaml"
        - "/api/doc"
        - "/api/doc.json"
        - "/api/docs/"
        - "/api/docs/index.html"
        - "/api/documentation"
        - "/api/index.html"
        - "/api/openapi.json"
        - "/api/openapi.yaml"
        - "/api/spec/swagger.json"
        - "/api/spec/swagger.yaml"
        - "/api/swagger"
        - "/api/swagger_doc.json"
        - "/api/swagger-api"
        - "/api/swagger-resources"
        - "/api/swagger-resources/restservices/v2/api-docs"
        - "/api/swagger-ui"
        - "/api/swagger-ui.html"
        - "/api/swagger-ui.json"
        - "/api/swagger-ui/"
        - "/api/swagger-ui/api-docs"
        - "/api/swagger-ui/swagger.json"
        - "/api/swagger-ui/swagger.yaml"
        - "/api/swagger.json"
        - "/api/swagger.yaml"
        - "/api/swagger.yml"
        - "/api/swagger/"
        - "/api/swagger/index"
        - "/api/swagger/index.html"
        - "/api/swagger/static/index.html"
        - "/api/swagger/swagger-ui.html"
        - "/api/swagger/ui/index"
        - "/api/swaggerapi"
        - "/api/v1/"
        - "/api/v1/api-docs"
        - "/api/v1/apidocs"
        - "/api/v1/swagger"
        - "/api/v1/swagger-ui"
        - "/api/v1/swagger-ui.html"
        - "/api/v1/swagger-ui.json"
        - "/api/v1/swagger-ui/"
        - "/api/v1/swagger-ui/swagger.json"
        - "/api/v1/swagger-ui/swagger.yaml"
        - "/api/v1/swagger.json"
        - "/api/v1/swagger.yaml"
        - "/api/v1/swagger/"
        - "/api/v2"
        - "/api/v2/api-docs"
        - "/api/v2/apidocs"
        - "/api/v2/swagger"
        - "/api/v2/swagger-ui"
        - "/api/v2/swagger-ui.html"
        - "/api/v2/swagger-ui.json"
        - "/api/v2/swagger-ui/"
        - "/api/v2/swagger.json"
        - "/api/v2/swagger/"
        - "/api/v3"
        - "/apidocs"
        - "/apidocs/"
        - "/apidocs/swagger.json"
        - "/doc/"
        - "/doc/swagger"
        - "/docs"
        - "/docs/index.html"
        - "/docs/swagger.json"
        - "/docs/swagger.yaml"
        - "/docu"
        - "/documentation"
        - "/documentation/swagger.json"
        - "/documentation/swagger.yaml"
        - "/error/..;/v1/api-docs"
        - "/error/..;/v2/api-docs"
        - "/error/..;/v3/api-docs"
        - "/help"
        - "/index/..;/v1/api-docs"
        - "/index/..;/v2/api-docs"
        - "/index/..;/v3/api-docs"
        - "/jeecg-boot/swagger-resources"
        - "/jeecg-boot/v2/api-docs"
        - "/jeecg-boot/v3/api-docs"
        - "/login/..;/v1/api-docs"
        - "/Login/..;/v1/api-docs"
        - "/login/..;/v2/api-docs"
        - "/Login/..;/v2/api-docs"
        - "/login/..;/v3/api-docs"
        - "/Login/..;/v3/api-docs"
        - "/openapi.json"
        - "/openapi.yaml"
        - "/openapi/v1/openapi.json"
        - "/openapi/v1/openapi.yaml"
        - "/rest/api-docs"
        - "/smartpay/swagger/core"
        - "/swagger"
        - "/swagger-api"
        - "/swagger-resources"
        - "/swagger-resources/configuration"
        - "/swagger-resources/configuration/security"
        - "/swagger-resources/configuration/ui"
        - "/swagger-resources/restservices"
        - "/swagger-resources/restservices/v2/api-docs"
        - "/swagger-ui"
        - "/swagger-ui-dist/"
        - "/swagger-ui-dist/index.html"
        - "/swagger-ui.html"
        - "/swagger-ui.json"
        - "/swagger-ui/"
        - "/swagger-ui/index"
        - "/swagger-ui/swagger.json"
        - "/swagger.json"
        - "/swagger.yaml"
        - "/swagger.yml"
        - "/swagger/"
        - "/swagger/api-docs"
        - "/swagger/core"
        - "/swagger/index.html"
        - "/swagger/static/index.html"
        - "/swagger/swagger-ui.html"
        - "/swagger/swagger-ui/"
        - "/swagger/swagger-ui/index.html"
        - "/swagger/ui/"
        - "/swagger/ui/index"
        - "/swagger/ui/index.html"
        - "/swagger/v1/swagger.json"
        - "/swagger/v1/swagger.yaml"
        - "/swagger/v2/swagger.json"
        - "/swagger/v2/swagger.yaml"
        - "/swaggerapi"
        - "/v1/..;/v2/api-docs"
        - "/v1/..;/v3/api-docs"
        - "/v1/swagger.json"
        - "/v1/swagger.yaml"
        - "/v2/..;/v1/api-docs"
        - "/v2/..;/v3/api-docs"
        - "/v2/api-docs"
        - "/v2/swagger.json"
        - "/v2/swagger.yaml"
        - "/v3/..;/v1/api-docs"
        - "/v3/..;/v2/api-docs"
        - "/webjars/swagger-ui/index.html"
        - "/..;/swagger-resources/configuration/security"
        - "/..;/swagger-resources/configuration/ui"
        - "/..;/swagger-ui"
        - "/..;/swagger-ui.html"
        - "/..;/swagger-ui/html"
        - "/..;/swagger-ui/index.html"
        - "/..;/swagger/codes"
        - "/..;/swagger/index.html"
        - "/..;/swagger/static/index.html"
        - "/..;/swagger/swagger-ui.html"
        - "/..;/swagger/ui"
        - "/..;/Swagger/ui/index"
        - "/..;/swagger/v1/swagger.json"
        - "/..;/swagger/v2/swagger.json"
        - "/..;/template/swagger-ui.html"
        - "/..;/user/swagger-ui.html"
        - "/..;/v1.1/swagger-ui.html"
        - "/..;/v1.2/swagger-ui.html"
        - "/..;/v1.3/swagger-ui.html"
        - "/..;/v1.4/swagger-ui.html"
        - "/..;/v1.5/swagger-ui.html"
        - "/..;/v1.6/swagger-ui.html"
        - "/..;/v1.7/swagger-ui.html"
        - "/..;/v1.8/swagger-ui.html"
        - "/..;/v1.9/swagger-ui.html"
        - "/..;/v1/api-docs"
        - "/..;/v2.0/swagger-ui.html"
        - "/..;/v2.1/swagger-ui.html"
        - "/..;/v2.2/swagger-ui.html"
        - "/..;/v2.3/swagger-ui.html"
        - "/..;/v2/api-docs"
        - "/..;/v2/swagger.json"
        - "/..;/v3/api-docs"
        - "/jeecg-boot/"


    headers:
      Accept: text/html
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'swagger:'
          - 'Swagger 2.0'
          - '"swagger":'
          - 'Swagger UI'
          - 'loadSwaggerUI'
          - '**token**:'
          - 'id="swagger-ui'
          - 'OpenAPI'
          - 'openapi:'
          - '"openapi":'
          - 'ReDoc'
          - 'swaggerVersion'
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - 'openapi[": ]*"?([0-9]+\.[0-9]+\.?[0-9]*)'
          - ' @version (v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})'
# digest: 4a0a0047304502206e693dd212a261c994aed1e1317abc0b7b6e066aebae42a1833ebf5086da5056022100d956be945d5c2b5fa96ea2ed37884f0b381e071abece12f73f2fba78e2dbf95c:922c64590222798bb761d5b6d8e72950